version: 'latest'

services:
  web:
    build: ./sums_sums
    volumes:
      - .:/sums_sums
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate --database=sums && gunicorn sums_sums.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - "./.env"
    depends_on:
      - db


  db:
    container_name: sums_pg
    image: postgres:14.1-alpine3.15
    environment:
      - POSTGRES_DB=$POSTGRES_AUTH_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./sums_sums/expense_tracker.sql:/docker-entrypoint-initdb.d/expense_tracker.sql
      
