# Generated by Django 5.1 on 2025-03-29 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('bank', models.TextField()),
                ('account_type', models.TextField(blank=True, null=True)),
                ('account_last_four', models.IntegerField(blank=True, null=True)),
                ('translator', models.JSONField()),
                ('date_formatter', models.TextField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
                ('category_display', models.TextField()),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshots',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_year', models.SmallIntegerField()),
                ('snapshot_month', models.SmallIntegerField()),
                ('snapshot_budget', models.JSONField()),
                ('snapshot_expenses', models.JSONField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('budget_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('recurring', models.BooleanField(blank=True, null=True)),
                ('account_nickname', models.TextField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
