# Generated by Django 5.1 on 2025-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgets',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
