# Generated by Django 5.1 on 2025-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
