# Generated by Django 5.1 on 2026-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sums', '0002_budgets_keywords_transactions_auto_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgets',
            name='annual_budget',
        ),
        migrations.AddField(
            model_name='budgets',
            name='budget_type',
            field=models.TextField(default='expense'),
        ),
    ]
