# Generated by Django 5.1 on 2025-03-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sums', '0003_remove_accounts_user_id_remove_budgets_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='budget',
            field=models.ForeignKey(blank=True, db_column='budget', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sums.budgets'),
        ),
    ]
